### ISSUE TITLE
Write proper .vapi files for Toxcore

### ISSUE THREAD

**Issue by SkyzohKey** [ValaTox/client#5]
# Write proper .vapi files for Toxcore
We need to write proper VAPI files (VAPI's) in order to be able to bind Toxcore in Vala. VAPI's are some simple files used by the Vala compiler (valac) to tell the C compiler which C function the Vala compiler will call. Here's the [definition by Gnome](https://wiki.gnome.org/Projects/Vala/LegacyBindings):

_Vala is designed to allow access to existing C libraries, especially GObject-based libraries, without the need for runtime bindings. Each to be used library requires a Vala API file (.vapi) at compile-time, containing the class and method declarations in Vala syntax._

## Why should we write proper VAPI's ?
We have to do it because the current VAPI's from Venom are outdated (toxcore API changes that made the old API broken). We have to do it to be able to develop a clean and easy2hack client. We have to do it because without this, the client wont ever be available.

## Why is this issue labeled with "help wanted" ?
I used this label 'cause writing a VAPI file is simple but really long for big-libraries (such as Toxcore). So I'll accept anyone to help me by: proposing code, contributing in debugging the VAPI's, paying me a bounty (to make me working on this issue at full-time) or even by opening another issue that reports mistake I could have made.

## How many times to make the VAPI's "stables" ?
It will depends on many factor: help received, bounties received, motivation, etc. Writing a VAPI file consist to create a line for each available method of the library to bind. This is simple but really long as fuck, so it can takes 2-3 days with help or 3 months without help.

## How can I contribute ?
You can contribute using this GitHub Repository to work on all the VAPI's related stuff:
https://github.com/ValaTox/tox-vapi

### Changes:
- [x] Setup a repository for creating the VAPI files.
- [x] Writing binding for the most useful functions, callbacks, enums, etc.
- [x] Fix the [compilation errors](https://github.com/ValaTox/tox-vapi/issues/2)
- [x] Testing the VAPI files.

**Comment by SkyzohKeyx** [comment]
Just finished to write the [toxcore.vapi](https://github.com/ValaTox/tox-vapi/blob/81e7aef86eec58e05868b777dcc827ccff5d8e54/src/toxcore.vapi). No I need to fix [a stupid compiling error](https://github.com/ValaTox/tox-vapi/issues/2) before being able to perform tests x)

**Comment by benwaffle** [comment]
we *really* need to do this

**Comment by SkyzohKeyx** [comment]
[**@benwaffle**](https://github.com/benwaffle) commented on [26 sept. 2015 05:49 UTC+2](https://github.com/ValaTox/client/issues/5#issuecomment-143395105 "2015-09-26T03:49:48Z - Replied by Github Comment Enhancer"):
> we *really* need to do this

Yes, this is sure!

**Comment by benwaffle** [comment]
In other news, the sky is blue.

**Comment by SkyzohKey** [comment]
_Removed useless posts._

**Comment by SkyzohKey** [comment]
Their is still errors at compiling. Need to fix this.

**Comment by SkyzohKey** [comment]
Errors are fixed, vapi is working like a charm, closing ! *-*
https://github.com/ValaTox/tox-vapi/tree/binding
