### ISSUE TITLE
Change application ID

### ISSUE THREAD

**Issue by benwaffle** [ValaTox/client#7]
Don't use `org.gnome` or `org.gtk` because this isn't a GNOME project

you could do `chat.tox.valatox`

**Comment by SkyzohKeyx** [comment]
Yes this was planned ^^'. I used `net.tox` but changed it to `org.gnome` to test gresources. Will update the files.

**Comment by SkyzohKeyx** [comment]
Fixed with [739e6bb1](https://github.com/ValaTox/client/commit/739e6bb1a2b2f54274ec7bc00f03578d4d66bf33).

**Comment by benwaffle** [comment]
You also need to change it in the gresource

**Comment by SkyzohKeyx** [comment]
Ah yes, i missed it ^^

**Comment by SkyzohKeyx** [comment]
Should be fixed with [ca28545e](https://github.com/ValaTox/client/commit/ca28545e1cbaa83c02166e95517f8bed2bd35fd8) and [1b963c69](https://github.com/ValaTox/client/commit/1b963c698b7949432b51b5ccc0c34d3e445d5a43). :)
